apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexclipper-service
  labels: 
    app: nexclipper-service
    version: v1
  namespace: nexclipper
spec:
  replicas: 1
  template:
    metadata:
      name: nexclipper-service
      labels:
        app: nexclipper-service
    spec:
      containers:
        - name: nexserivce
          image: nexclipper/nexservice:0.1.0
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              name: nex-service
          env:
            - name: MYSQL_DBNAME
              value: "defaultdb"
            - name: MYSQL_URL
              value: "mysql.nexclipper"
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_USERNAME
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: REDIS_ENDPOINT
              value: "redis.nexclipper"
            - name: REDIS_PORT
              value: '6379'
            - name: TSDB
              value: "influx"
            - name: INFLUXDB_ENDPOINT
              value: "http://influx.nexclipper:8087"
            - name: INFLUXDB_DATASOURCE
              value: "nexclipper"
            - name: ACTIVE
              value: "dev"

