collectorapiVersion: v1
kind: Service
metadata:
  name: nexclipper-collector
  labels:
    app: nexclipper-collector
    version: v0.1
  namespace: nexclipper
spec:
  type: NodePort
  ports:
  - port: 10100
    protocol: TCP
    targetPort: 9000
    nodePort: 32100
    name: http
  selector:
    app: nexclipper-collector
